lib/tracker_web/router.ex
defmodule TrackerWeb.Router do
  use TrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
   #  plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :get_current_user
   
  end

  
   # Below the pipeline
  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  pipeline :csrf do
    plug :protect_from_forgery # to here
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/task", PageController, :task    

    resources "/users", UserController
    resources "/tasks", TaskController
    
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete

    pipe_through :api
   
    resources "/manages", ManageController, except: [:new, :edit]
    resources "/timeblocks", TimeblockController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TrackerWeb do
  #   pipe_through :api
  # end
end

lib/tracker_web/templates/page/index.html.eex
<h3>Welcome to Task Tracker</h3>
<!-- session_path(@conn, :create) -->
<%= form_tag("/session", method: :post) do %>
  <%= if @current_user do %>
    <p><span><%= link "All Users", to: user_path(@conn, :index), class: "btn btn-default" %></span></p>
    <%= if length(@underlings) > 0 do %>
      <p><span><%= link "All Tasks", to: task_path(@conn, :index), class: "btn btn-default" %></span></p>
    <% end %>
    <p><span><%= link "Task Manager", to: page_path(@conn, :task), class: "btn btn-primary" %></span></p>
  <% else %>
   <div class="form-group">
     Email
   <input type="email" name="email" placeholder="user@example.com" >
   </div>
   <!-- passwords come later -->
   <div class="form-group">
     <p><button class="btn btn-primary">Log in</button></p>
     <span>Not a user yet? <%= link "Register", to: user_path(@conn, :new) %></span>
   </div>
  <% end %>
<% end %>

lib/tracker_web/templates/page/task.html.eex
<%= if @current_user do %>
  <%= if length(@underlings) > 0 do %>
    <h1>New Task</h1>
    <div class="row">
      <div class="col">
        <%= render TrackerWeb.TaskView, "form.html",
            Map.put(assigns, :action, task_path(@conn, :create)) %>
      </div>
    </div>
  <% end %>
  <%= if length(@task_report) > 0 do %>
    <h1> Underlings Task Report </h2>
    <table class="table">
      <thead>
        <tr>
          <th>Task</th>
          <th>User</th>
          <th>Description</th>
          <th>Completed?</th>
        <tr>
      </thead>
      <tbody>
        <%= for task <- @task_report do %>
          <tr>
            <td><%= task.title %></td>
            <td><%= task.user.name %></td>
            <td><%= task.description  %></td>
            <td><%= task.is_completed %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <h1>Your Tasks</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Minutes</th>
        <th>Is completed</th>
        <th></th>
    </tr>
  </thead>
  <tbody>
  <%= for task <- @tasks do %>
    <%= if task.user_id == @current_user.id do %> 
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= task.minutes %></td>
      <td><%= task.is_completed %></td>
      <td class="text-right">
        <span><%= link "Update Minutes", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
        <%= if length(@underlings) > 0 do %>
          <span><%= link "Assign", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
        <% end %>
        <span><%= link "Mark Complete", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
      </td>
    </tr>
  <% end %>
  <% end %>
  </tbody>
</table>    
<% end %>